using System;

namespace FutureConcepts.Media.Client.StreamViewer
{
    /// <summary>
    /// Used to encapsulate a request to move a PTZ camera, generated by the a StreamViewerControl
    /// </summary>
    public class PTZMoveRequestEventArgs : EventArgs
    {
        /// <summary>
        /// Creates a new instance, with a relative change in pan and tilt
        /// </summary>
        /// <param name="pan">pan amount, in degrees</param>
        /// <param name="tilt">tilt amount, in degrees</param>
        public PTZMoveRequestEventArgs(double pan, double tilt)
            : base()
        {
            Pan = pan;
            Tilt = tilt;
            Zoom = 0;
            IsAbsolute = false;
        }

        /// <summary>
        /// Creates a new instance, with a relative change in pan, tilt, and zoom.
        /// </summary>
        /// <param name="pan">pan amount, in degrees</param>
        /// <param name="tilt">tilt amount, in degrees</param>
        /// <param name="zoom">zoom amount, in degrees</param>
        public PTZMoveRequestEventArgs(double pan, double tilt, double zoom)
            : base()
        {
            Pan = pan;
            Tilt = tilt;
            Zoom = zoom;
            IsAbsolute = false;
        }

        /// <summary>
        /// Requested Pan
        /// </summary>
        public double Pan { get; set; }

        /// <summary>
        /// Requested Tilt
        /// </summary>
        public double Tilt { get; set; }

        /// <summary>
        /// Requested Zoom. If 0, then it is always ignored.
        /// </summary>
        public double Zoom { get; set; }

        /// <summary>
        /// If true, then the PTZ values indicated are absolute, if false, then they are relative
        /// </summary>
        public bool IsAbsolute { get; set; }
    }
}
