using System;
using System.ComponentModel;
using FutureConcepts.Media.Contract;

namespace FutureConcepts.Media
{
    /// <summary>
    /// Used to express a Microwave receiver frequency user-defined preset
    /// kdixon 02/09/2009
    /// </summary>
    [Serializable]
    public class MicrowaveTuningPreset : UserPresetItem
    {
        /// <summary>
        /// Creates a new instance
        /// </summary>
        public MicrowaveTuningPreset() { }

        /// <summary>
        /// Creates a new instance, set to a specific frequency
        /// </summary>
        /// <param name="tuning">Microwave frequency, in MHz</param>
        public MicrowaveTuningPreset(MicrowaveTuning tuning)
        {
            this.Tuning = tuning;
            this.Name = this.ToString();
        }

        private MicrowaveTuning _tuning;
        /// <summary>
        /// The frequency, in MHz
        /// </summary>
        public MicrowaveTuning Tuning
        {
            get
            {
                return _tuning;
            }
            set
            {
                _tuning = value;
            }
        }

        private int _index = -1;
        /// <summary>
        /// When corresponding to an index on the device, this value will be != -1
        /// </summary>
        public int Index
        {
            get
            {
                return _index;
            }
            set
            {
                _index = value;
            }
        }

        private bool _autoGenerated;
        /// <summary>
        /// If this field is true, then this preset can be wiped out during a scan for new presets.
        /// If the user edits the properties in this struct, then it should be set to false
        /// </summary>
        [DefaultValue(false)]
        public bool AutoGenerated
        {
            get
            {
                return _autoGenerated;
            }
            set
            {
                _autoGenerated = value;
            }
        }

        /// <summary>
        /// Generates a string representation of this preest.
        /// </summary>
        /// <returns>If name is not set, then returns "<see cref="P:Frequency"/> MHz"</returns>
        public override string ToString()
        {
            if (this.Tuning != null)
            {
                if (this.Name != null)
                {
                    if (this.Name.Equals(this.Tuning.FrequencyMHz + " MHz"))
                    {
                        return this.Name;
                    }
                }
                return this.Tuning.FrequencyMHz + " MHz" + ((this.Name != null) ? (Environment.NewLine + this.Name) : "");
            }
            else if (!string.IsNullOrEmpty(this.Name))
            {
                return this.Name;
            }
            else if (this.Index >= 0)
            {
                return "Preset " + this.Index;
            }
            
            return "Unknown Microwave Preset";
        }
    }
}
