//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebVideoViewer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class client
    {
        public int id { get; set; }
        public string moniker { get; set; }
        public string agency { get; set; }
        public string subnet { get; set; }
        public short min_ip { get; set; }
        public short max_ip { get; set; }
        public sbyte is_active { get; set; }
        public string device_id { get; set; }
    }
}
