//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebVideoViewer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class online_clients
    {
        public int client_id { get; set; }
        public long last_reported { get; set; }
    }
}
