//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebVideoViewer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class source
    {
        public int id { get; set; }
        public int client_id { get; set; }
        public string device_source_url { get; set; }
        public string source_name { get; set; }
        public string restream_source_url { get; set; }
        public string source_description { get; set; }
        public string camera_control_address { get; set; }
        public bool has_audio { get; set; }
        public string mime_type { get; set; }
    }
}
